# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back', 'rb'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
import json

ROBOT_POSE_DATA_DIR = 'robot_pose_data_json'

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print (classes)

['Back', 'Belly', 'Crouch', 'Frog', 'HeadBack', 'Knee', 'Left', 'Right', 'Sit', 'Stand', 'StandInit']


In [3]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = json.load(open(filename, 'rb'))
    target = [i] * len(data)
    return data, target

In [ ]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE
for i in range(len(classes)):
    data, target = load_pose_data(i)
    all_data.extend(data)
    all_target.extend(target)
    #all_data += data
    #all_target += target

print ('total number of data', len(all_data))
#print(all_data)

total number of data 222
[[-0.05058002471923828, -0.2269899845123291, -0.8298521041870117, 1.7180380821228027, -0.05058002471923828, -0.1487560272216797, -0.9311800003051758, 1.8945322036743164, -0.008992496877908707, -1.516520619392395], [-0.05058002471923828, -0.2269899845123291, -0.8298521041870117, 1.7180380821228027, -0.05058002471923828, -0.1487560272216797, -0.9311800003051758, 1.8960661888122559, -0.006883446592837572, -1.5203558206558228], [-0.05058002471923828, -0.2269899845123291, -0.8298521041870117, 1.7165040969848633, -0.05058002471923828, -0.1487560272216797, -0.9311800003051758, 1.8945322036743164, -0.006883446592837572, -1.520164132118225], [-0.05058002471923828, -0.2269899845123291, -0.8298521041870117, 1.7165040969848633, -0.05058002471923828, -0.1487560272216797, -0.9311800003051758, 1.8945322036743164, -0.007075135130435228, -1.5199724435806274], [-0.05058002471923828, -0.2269899845123291, -0.8298521041870117, 1.7165040969848633, -0.05058002471923828, -0.1487560272

In [49]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [50]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [51]:
# YOUR CODE HERE
#clf.fit(all_data, all_target)
X_train, X_test, Y_train, Y_test = train_test_split(all_data, all_target, test_size= 0.3)
clf.fit(X_train, Y_train)

SVC(C=100.0, gamma=0.001)

### predicting

In [52]:
clf.predict(all_data[-1:]), all_target[-1:]

(array([10]), [10])

In [53]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [54]:
expected = []
predicted = []
# YOUR CODE HERE
#clf.fit(all_data, all_target)
#expected = all_target
#predicted = clf.predict(all_data)
predicted = clf.predict(X_train)
expected = Y_train

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        22
           3       1.00      1.00      1.00         6
           4       1.00      1.00      1.00         7
           5       1.00      1.00      1.00         8
           6       1.00      1.00      1.00        14
           7       1.00      1.00      1.00         6
           8       1.00      1.00      1.00        15
           9       1.00      1.00      1.00         8
          10       1.00      1.00      1.00        37

    accuracy                           1.00       155
   macro avg       1.00      1.00      1.00       155
weighted avg       1.00      1.00      1.00       155


Confusion matrix:
[[18  0  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0  0]
 

## 4. Evaluate on the test data

In [55]:
expected = []
predicted = []
# YOUR CODE HERE
predicted = clf.predict(X_test)
expected = Y_test

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5
           2       0.89      1.00      0.94         8
           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         3
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         6
           7       1.00      0.80      0.89         5
           8       1.00      1.00      1.00        11
           9       1.00      1.00      1.00         3
          10       1.00      1.00      1.00        15

    accuracy                           0.99        67
   macro avg       0.99      0.98      0.98        67
weighted avg       0.99      0.99      0.98        67


Confusion matrix:
[[ 5  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0]
 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [56]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
#pickle.dump(clf, open(ROBOT_POSE_CLF, 'wb'))
with open(ROBOT_POSE_CLF, "wb") as f:
    pickle.dump(clf, f)

Then, in the application we can load the trained classifier again.

In [57]:
#clf2 = pickle.load(open(ROBOT_POSE_CLF))
with open(ROBOT_POSE_CLF, "rb") as f:
    clf2 = pickle.load(f)

clf2.predict(all_data[-1:]), all_target[-1:]

(array([10]), [10])